/**:
  ros__parameters:
    # number of cameras to use
    # num_cameras: 4
    # NOTE: This parameter is specified in yolo.launch.py.
    # subscribe to depth topics
    subscribe_depth: false
    # Use custom image transport for color and depth images
    color_transport: compressed
    depth_transport: compressedDepth
    # detection frequency; Hz
    rate: 10.0
    # path to YOLO model weights in PT format (required)2
    model: $(find-pkg-share kalman_yolo)/models/urc2024.pt
    # whether to convert incoming images to grayscale before inference
    grayscale: false
    # detection threshold
    confidence_threshold: 0.8
    # list of class names
    class_names:
    - bottle
    - mallet
    # average real life half-width of each class in meters
    class_radii:
    - 0.1
    - 0.13
    # maximum 3D distance between two detections of the same class to consider them the same
    merge_radius: 2.0
    # number of history frames to use for temporal filtering; Higher
    temporal_window: 10
    # number of times a detection must be present in the history to pass through the filter; Must be less than or equal to temporal_window. Setting it to 0 will result in lack of entry filtering and setting it to temporal_window value will provide no exit filtering. Entry filtering is useful for preventing false positives from being reported, while exit filtering is useful for preventing existing detections from jumping around and disappearing. If you are not sure what value to use, choose temporal_window / 2 which corresponds to a detection being present half of the time.
    temporal_threshold: 5
    # Publish detection results as TF2 transforms.
    publish_tf: true
    # Publish annotated images on annotatedX topics.
    publish_annotated: true
    annotated_transport: compressed
